parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Y661":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var t=function(){window.NodeList&&!NodeList.prototype.forEach&&(NodeList.prototype.forEach=function(t,o){o=o||window;for(var e=0;e<this.length;e++)t.call(o,this[e],e,this)})};exports.default=t;
},{}],"nhXd":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){var e=document.querySelector(".js-header-menu__btn"),t=document.querySelector(".js-header-menu");null==e||e.addEventListener("click",function(){null==t||t.classList.toggle("header-menu__animate"),null==e||e.classList.toggle("header-menu__btn-animate")})};exports.default=e;
},{}],"vQ81":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){var e,t;window,e={slides:document.querySelectorAll("#slideshow figure"),captions:document.getElementsByTagName("figcaption")},t={get:0,set:function(n){t.reset(e.slideNav),t.reset(e.slides),e.slideNav[n].className="slide",e.slides[n].className="show"},reset:function(e){for(var t=0,n=e.length;t<n;++t)e[t].removeAttribute("class")},auto:function(){++t.get,e.slides.length===t.get?(t.set(0),t.get=0):t.set(t.get)}},function(){for(var n=document.createElement("ul"),s=0,l=e.slides.length;s<l;++s){var a=document.createElement("a");a.href="",n.appendChild(a)}document.getElementById("slideshow").appendChild(n),e.slideNav=document.querySelectorAll("#slideshow ul a"),t.set(t.get);for(var i=0;i<e.captions.length;)e.captions[i].innerHTML=e.captions[i].innerHTML.trim(),""===e.captions[i].innerHTML?e.captions[i].remove():++i;for(var r=function(n,s){e.slideNav[n].addEventListener("click",function(e){e.preventDefault(),t.set(n),t.get=n,clearInterval(d),d=setInterval(t.auto,5e3)})},o=0,c=e.slideNav.length;o<c;++o)r(o);var d=setInterval(t.auto,5e3)}()};exports.default=e;
},{}],"udc5":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){var e=document.querySelector(".slider-js-badges"),t=document.querySelector(".top__badges-slider-index"),n=(document.querySelector(".top__badges-slider-array"),new Flickity(e,{cellAlign:"left",contain:!0,pageDots:!1,draggable:!1})),r=function(){var e=n.selectedIndex+1;t.textContent=e+"/"+n.slides.length};r();var l=document.querySelector(".carousel--prev");null==l||l.addEventListener("click",function(){n.previous()});var c=document.querySelector(".carousel--next");null==c||c.addEventListener("click",function(){n.next()}),n.on("select",r)};exports.default=e;
},{}],"Jpp1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){var e=document.querySelector(".arrow-top"),t=document.documentElement;null==e||e.addEventListener("click",function(){t.scrollTo({top:0,behavior:"smooth"})}),document.addEventListener("scroll",function(){var o=t.scrollHeight-t.clientHeight;t.scrollTop/o>.1?null==e||e.classList.add("showBtn"):null==e||e.classList.remove("showBtn")})};exports.default=e;
},{}],"Rgmk":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});var t=e(require("./components/forEachPolyfill")),o=e(require("./components/nav")),r=e(require("./components/slider")),n=e(require("./components/flickity")),u=e(require("./components/arrowTop"));document.addEventListener("DOMContentLoaded",function(){t.default(),o.default(),r.default(),n.default(),u.default()},!1);
},{"./components/forEachPolyfill":"Y661","./components/nav":"nhXd","./components/slider":"vQ81","./components/flickity":"udc5","./components/arrowTop":"Jpp1"}]},{},["Rgmk"], null)
//# sourceMappingURL=/js/index.js.map